version: '3.8'

services:
  auth-service:
    build:
      context: ./auth
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres

  redis:
    image: redis:7
    ports:
      - "6379:6379"
      -
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: skilltracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
