spring:
  datasource:
    url:
    username:
    password:
  liquibase:
    change-log: classpath:liquibase/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host:
      port:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:

server:
  servlet:
    context-path: /api
  port: 8080

jwt:
  secret:
  expiration:

springdoc:
  swagger-ui:
    path: /swagger-ui.html

cors:
  origins: