rate-limiter:
  enabled: true

spring:
  datasource:
    url:
    username:
    password:
  liquibase:
    change-log: classpath:liquibase/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            client-name: Google
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
          yandex:
            client-id:
            client-secret:
            client-name: Yandex
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - login:email
              - login:info
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: id

server:
  servlet:
    context-path: /api
  port: 8080

jwt:
  secret:
  expiration:

springdoc:
  swagger-ui:
    path: /swagger-ui.html

cors:
  origins:

logging:
  level:
    org.springframework.security: DEBUG

application:
  url:

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true